const MovieCollection = [
  {
    id: "a1",
    name: "Ruby Lipstick",
    description: "Red Lipstick",
    price: "$12.99",
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },
  {
    id: "a2",
    name: "Emerald Lipstick",
    description: "Green lipstick",
    price: 11.99,
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },
  {
    id: "a3",
    name: "Sunlight Lipstick",
    description: "Yellow Lipstick",
    price: 10.99,
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },
  {
    id: "a4",
    name: "Meadow Lipstick",
    description: "A Green Shade",
    price: 18.99,
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },
  {
    id: "a5",
    name: "Orange Lipstick",
    description: "Smells like oranges",
    price: 22.99,
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },
  {
    id: "a6",
    name: "Black Lipstick",
    description: "For the Hreat of Darkness",
    price: 2.0,
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },
  {
    id: "a7",
    name: "Food Lipstick",
    description: "I'm Hungry",
    price: 13.99,
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },
  {
    id: "a8",
    name: "Red Death",
    description: "For those who like to go fast",
    price: 18.99,
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },

  {
    id: "a9",
    name: "Thunderlord",
    description: "Lightening Strikes Twice",
    price: 22.99,
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },
  {
    id: "a10",
    name: "Bad Juju",
    description: "Good or Bad, Depends on how you look at it",
    price: 19.18,
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },
  {
    id: "a11",
    name: "Endless",
    description: "Smells like oranges",
    price: 22.99,
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },
  {
    id: "a12",
    name: "Black Death",
    description: "For the Hreat of Darkness",
    price: 2.0,
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },
  {
    id: "a13",
    name: "The Imperium",
    description: "I'm Hungry",
    price: 13.99,
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },
  {
    id: "a14",
    name: "Night Lords",
    description: "For those who like to go fast",
    price: 18.99,
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },

  {
    id: "a15",
    name: "End Thunderlord",
    description: "Lightening Strikes Twice",
    price: 22.99,
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },
  {
    id: "a16",
    name: "Alpha Legion",
    description: "Good or Bad, Depends on how you look at it",
    price: 19.18,
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },
  {
    id: "a17",
    name: "Iron Warriors",
    description: "Lightening Strikes Twice",
    price: 22.99,
    url: "https://via.placeholder.com/150",
    imgurl: "https://via.placeholder.com/150",
  },
];

export default MovieCollection; 